### PR TITLE
Add dotenv to the list of pydantic hidden imports

### LINKED ISSUE #523: Pydantic hook does not include optional dotenv dependency
**Describe the bug**
* Which hook/library isn't working? Pydantic
* Does the error get raised while building or when running?

```
ModuleNotFoundError: No module named 'dotenv'

ImportError: python-dotenv is not installed, run `pip install pydantic[dotenv]`
[3019] Failed to execute script 'pcb_dr' due to unhandled exception!
```

**To Reproduce**

A minimal example file:
```py
from pydantic import BaseSettings


class MySettings(BaseSettings):
    FOO: str

    class Config:
        env_file = '.env'


def main() -> None:
    settings = MySettings()
    print(settings.FOO)


if __name__ == "__main__":
    main()
```

And create a small `.env` file:

```
FOO=BAR
```

PyInstaller command:
```
pyinstaller --onefile main.py
```

**Expected behavior**

Running outside Pyinstaller:

```
$ python main.py
BAR
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Python Version: 3.10.8
 - Version of `pyinstaller-hooks-contrib`: 2022.13
 - Version of PyInstaller: 5.6.2

**Additional context**

```
$ pip list
Package                   Version
------------------------- -------
altgraph                  0.17.3
macholib                  1.16.2
pip                       22.3.1
pydantic                  1.10.2
pyinstaller               5.6.2
pyinstaller-hooks-contrib 2022.13
python-dotenv             0.21.0
setuptools                65.6.3
typing_extensions         4.4.0
wheel                     0.38.4
```

You can see here in the Pydantic source that the import is hidden:

- https://github.com/pydantic/pydantic/blob/v1.10.2/pydantic/env_settings.py#L326

Documentation on this feature:

- https://pydantic-docs.helpmanual.io/usage/settings/#dotenv-env-support

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #523

### CODE REVIEW

**Comment by johnthagen** [comment]
@rokm Do you think this should be put outside the `if is_compiled:` block instead?

**Comment by rokm** [comment]
> @rokm Do you think this should be put outside the `if is_compiled:` block instead?

No, if `pydantic` is not cython-compiled, it should be picked up automatically.

**Comment by rokm** [comment]
Maybe add an "update" news fragment for the next release's change log?

**Comment by johnthagen** [comment]
> Maybe add an "update" [news fragment](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/news/README.txt) for the next release's change log?

👍 Done.

**Comment by bwoodsend** [comment]
No no no, it goes in a fragment file (in this case `news/524.update.rst`). The link to the PR/issue is automatic. Otherwise that changelog file would cause no end of merge conflicts.

**Comment by johnthagen** [comment]
> No no no, it goes in a fragment file

Sorry about that 😄.

Hopefully it is correct now? If you could squash the commits using the GitHub UI if/when this is merged, that would be great!

**Review by bwoodsend — APPROVED** [review]

**Comment by bwoodsend** [comment]
Thanks @johnthagen!

**Pull request merged**
