### PR TITLE
hooks: add hook for langdetect and swagger_spec_validator

### PR DESCRIPTION
**Pull request by eric15342335**
#285 and #296
I seems can not run the workflow
sshot-001

### CODE REVIEW

**Comment by bwoodsend** [comment]
>  I seems can not run the workflow

This is rather odd. The actions for both [the master repo](https://github.com/pyinstaller/pyinstaller-hooks-contrib/actions/) and [my fork](https://github.com/bwoodsend/pyinstaller-hooks-contrib/actions/) are behaving normally so it appears to be specific to your fork but your master branch is even with ours so I don't see what the difference could be. In [eric15342335/pyinstaller-hooks-contrib/settings/actions](https://github.com/eric15342335/pyinstaller-hooks-contrib/settings/actions), do you have *Allow all actions* selected? That's what we have.

**Review by bwoodsend — CHANGES_REQUESTED** [review]
We need news entries for each one. Use the issue numbers instead of the PR numbers in the news entries' filenames.

**Comment by bwoodsend** [comment]
I'd prefer that each news entry was added in the same commit as the hook and test rather than an extra *add news item* commit but it's not that important. I've triggered CI from my own fork for now. https://github.com/bwoodsend/pyinstaller-hooks-contrib/actions/runs/1162353622

**Comment by bwoodsend** [comment]
@eric15342335 I'd like to add you to the PyInstaller team and give you basic triaging permissions. Basically you'd be able to do what I do here - make sure new pull requests make sense and have tests and news entries. Then I'll eventually give you push access so that you can start merging yourself too. You'll also be able to do the same on the main PyInstaller repo too. Sound OK?

**Comment by eric15342335** [comment]
Sounds pretty good, thank you!

**Comment by bwoodsend** [comment]
OK, let me work out who has permission to grant other people permissions...

**Comment by bwoodsend** [comment]
In theory, you should have received an invite. Could you also [send me an email](mailto:bwoodsend@gmail.com?Subject=Joining%20PyInstaller&Body=Hello%2C%20I%27m%20Eric.) so that I can send you a link to the Discord channel we use to talk to each other.

**Pull request merged**
