### PR TITLE
Add hook for parsedatetime

### PR DESCRIPTION
**Pull request by bwoodsend**
Fixes [4995](https://github.com/pyinstaller/pyinstaller/issues/4995).

I've not really tested it to death. Anything you'd particularly want it tested for?

### CODE REVIEW

**Comment by bwoodsend** [comment]
Ahh very neat. Gets rid of that ugly `try except` too. I take it you'd rather I squashed these updates into the previous commit so that it's still just the one commit for this PR?

**Comment by Legorooj** [comment]
@bwoodsend don't bother; I can squash merge it as a single commit.

**Comment by bwoodsend** [comment]
There we go

**Comment by Legorooj** [comment]
Thanks for this!

**Pull request merged**
