### PR TITLE
hook: update shapely hook for compatibility with v.1.8.1

### LINKED ISSUE #388: hook-shapely.py breaks on Windows with Shapely 1.8.1.pre1
**Describe the bug**

The Shapely project updated their wheel building pipeline for Shapely 1.8.1.pre1, which has resulted in some change that appears to break hook-shapely on Windows.

Here is the log from a GitHub runner:
```
2022-02-21T22:23:02.6800455Z D:\a\vpype\vpype>pyinstaller --noconfirm --onedir     --name vpype --icon="scripts/vpype.ico"     --add-data="vpype/vpype_config.toml;vpype"     --add-data="vpype_viewer/shaders;vpype_viewer/shaders"     --add-data="vpype_viewer/resources;vpype_viewer/resources"     --add-data="vpype_viewer/qtviewer/resources;vpype_viewer/qtviewer/resources"     --additional-hooks-dir=scripts/hooks     scripts/run_vpype.py 
2022-02-21T22:23:03.1613246Z 194 INFO: PyInstaller: 4.9
2022-02-21T22:23:03.1613874Z 194 INFO: Python: 3.9.9
2022-02-21T22:23:03.1705430Z 203 INFO: Platform: Windows-10-10.0.17763-SP0
2022-02-21T22:23:03.1711830Z 204 INFO: wrote D:\a\vpype\vpype\vpype.spec
2022-02-21T22:23:03.1744368Z 207 INFO: UPX is not available.
2022-02-21T22:23:03.1756144Z 209 INFO: Extending PYTHONPATH with paths
2022-02-21T22:23:03.1756630Z ['D:\\a\\vpype\\vpype\\scripts']
2022-02-21T22:23:03.4537930Z 487 INFO: checking Analysis
2022-02-21T22:23:03.4538655Z 487 INFO: Building Analysis because Analysis-00.toc is non existent
2022-02-21T22:23:03.4539267Z 487 INFO: Initializing module dependency graph...
2022-02-21T22:23:03.4564823Z 489 INFO: Caching module graph hooks...
2022-02-21T22:23:03.4719700Z 505 INFO: Analyzing base_library.zip ...
2022-02-21T22:23:06.8982891Z 3931 INFO: Processing pre-find module path hook distutils from 'd:\\a\\vpype\\vpype\\.venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
2022-02-21T22:23:06.8986367Z 3931 INFO: distutils: retargeting to non-venv dir 'C:\\hostedtoolcache\\windows\\Python\\3.9.9\\x64\\lib'
2022-02-21T22:23:12.3823203Z 9415 INFO: Caching module dependency graph...
2022-02-21T22:23:12.5949918Z 9628 INFO: running Analysis Analysis-00.toc
2022-02-21T22:23:12.6284347Z 9661 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
2022-02-21T22:23:12.6285172Z   required by d:\a\vpype\vpype\.venv\scripts\python.exe
2022-02-21T22:23:13.3563093Z 10389 INFO: Analyzing D:\a\vpype\vpype\scripts\run_vpype.py
2022-02-21T22:23:14.9420057Z 11975 INFO: Processing pre-find module path hook site from 'd:\\a\\vpype\\vpype\\.venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
2022-02-21T22:23:14.9423879Z 11975 INFO: site: retargeting to fake-dir 'd:\\a\\vpype\\vpype\\.venv\\lib\\site-packages\\PyInstaller\\fake-modules'
2022-02-21T22:23:19.1140723Z 16147 INFO: Processing pre-safe import module hook setuptools.extern.six.moves from 'd:\\a\\vpype\\vpype\\.venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-setuptools.extern.six.moves.py'.
2022-02-21T22:23:24.5748361Z 21608 INFO: Processing pre-safe import module hook six.moves from 'd:\\a\\vpype\\vpype\\.venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
2022-02-21T22:23:32.1986105Z 29231 INFO: Processing module hooks...
2022-02-21T22:23:32.1986854Z 29232 INFO: Loading module hook 'hook-pnoise.py' from 'D:\\a\\vpype\\vpype\\scripts\\hooks'...
2022-02-21T22:23:32.2832770Z 29316 INFO: Determining a mapping of distributions to packages...
2022-02-21T22:23:40.4558284Z 37489 INFO: Packages required by pnoise:
2022-02-21T22:23:40.4558810Z ['numpy', 'setuptools']
2022-02-21T22:23:40.4576319Z 37491 INFO: Loading module hook 'hook-vpype.py' from 'D:\\a\\vpype\\vpype\\scripts\\hooks'...
2022-02-21T22:23:40.4596695Z 37493 INFO: Loading module hook 'hook-jinja2.py' from 'd:\\a\\vpype\\vpype\\.venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
2022-02-21T22:23:40.4601248Z 37493 INFO: Loading module hook 'hook-py.py' from 'd:\\a\\vpype\\vpype\\.venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
2022-02-21T22:23:40.6930326Z 37725 INFO: Loading module hook 'hook-pytest.py' from 'd:\\a\\vpype\\vpype\\.venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
2022-02-21T22:23:40.9084755Z 37941 INFO: Loading module hook 'hook-shapely.py' from 'd:\\a\\vpype\\vpype\\.venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
2022-02-21T22:23:40.9144032Z Error: geos_c.dll not found, required by hook-shapely.py.
2022-02-21T22:23:40.9144780Z Please check your installation or provide a pull request to PyInstaller to update hook-shapely.py.
```

[Corresponding GH Action run](https://github.com/abey79/vpype/runs/5280624719?check_suite_focus=true)

The exact same setup works with Shapely 1.8.0.

I have opened an issue on Shapely's side (shapely/shapely#1326), but it appears that the change is expected.

**Desktop:**
 - OS: GitHub windows-latest runner
 - Python Version: 3.9
 - Version of `pyinstaller-hooks-contrib`: 2022.2
 - Version of PyInstaller: 4.9

### PR DESCRIPTION
**Pull request by rokm**
Fixes #388.

### CODE REVIEW

**Comment by rokm** [comment]
This is nightmare-grade stuff, but unfortunately, I have a project using `shapely` that ends up being frozen for Windows, so I guess this will need to be sorted out sooner or later...

Here's the one-shot test: https://github.com/rokm/pyinstaller-hooks-contrib/actions/runs/1938049542

The remaining failures on `ubuntu` are due to wheels for older shapely version not being available for newer python versions (so we try to build from sdist, which requires system-installed libgeos). The same thing happens on Windows, but there pip install seems to not exit with error, so we skip the tests and pretend that everything is fine.

On macOS, the 1.6.4 version fails with python 3.7 due to `libc` is not being visible on Big Sur for that python version. Other cases are again missing wheels (and installing from sdist would require libgeos installed via `brew`, which we could do - but then it would probably mask the issues with incorrect bundling of shared libraries due to search path fallbacks). Lastly, 1.8.1 fails on 3.10 because for some reason, shapely provides only arm64 wheels for that one.

**Comment by rokm** [comment]
Also, I'm particularly unhappy with the macOS "solution" of having to duplicate the dylibs to make things work. This is a problem in disguise and will likely result in tears in some circumstances (two copies of the same lib being loaded). But I guess for now, it is better than things not working at all. Sorting this out will require support for symlinks and/or binary dependency scanner preserving the original sub-directory layout. (Although on the other hand, `codesign` will likely also have its complaints about directories being named `.dylibs` and `Shapely.libs`, but that's not a shapely-specific problem...).

**Comment by bwoodsend** [comment]
Would anyone be able distribute a bundle containing symlinks? Putting symlinks into a zip file just duplicates the file. I doubt that macOS's `.pkg` archives handle them any differently. Possibly they could be made on the fly by a runtime hook but that would fail if the bundle was installed somewhere non-writeable.

**Review by bwoodsend — APPROVED** [review]

**Comment by rokm** [comment]
> Would anyone be able distribute a bundle containing symlinks? Putting symlinks into a zip file just duplicates the file. I doubt that macOS's `.pkg` archives handle them any differently. Possibly they could be made on the fly by a runtime hook but that would fail if the bundle was installed somewhere non-writeable.

I think symlinks should not be a problem on macOS, because they are present elsewhere as well (for example, in .framework bundles, Current is usually a symlink to specific Version). And our `BUNDLE()` also reallocates some stuff and creates symlinks to original locations, so I assume whatever archive format is used to distribute these properly handles symbolic links. 

Also (and I didn't know that before), `zip` apparently supports symlinks with `--symlinks` / `-y` option.

**Comment by abey79** [comment]
Is it known when this will be released?

**Comment by abey79** [comment]
Thanks! 🎉

**Pull request merged**
