### PR TITLE
Add hook-cloudscraper.py

### PR DESCRIPTION
**Pull request by eric15342335**
Add a hook for `cloudscraper` to collect data files.
Data is located at [cloudscraper\user_agent\browsers.json](https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/user_agent/browsers.json).
[ci](https://github.com/eric15342335/pyinstaller-hooks-contrib/actions/runs/1084697166)

### CODE REVIEW

**Comment by bwoodsend** [comment]
You'll have to rebase this to deal with the merge conflict. Other than that - looks good.

**Comment by bwoodsend** [comment]
Just for the record: [A test run](https://github.com/bwoodsend/pyinstaller-hooks-contrib/actions/runs/1084900753).

**Comment by bwoodsend** [comment]
Ah, I'm afraid that just made it worse. Don't use merge commits to rebase in future. Instead Use rebase merge and mop up the conflicts manually.

**Comment by bwoodsend** [comment]
I've just pushed it rebased no no need to do it again here.

**Comment by eric15342335** [comment]
thank you very much

**Pull request merged**
