### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by LP-Codes**
Added html test runner hook which fixes report generation when used with unit-testing

### CODE REVIEW

**Comment by LP-Codes** [comment]
Added html test runner hook which fixes report generation when used with unit-testing

**Comment by LP-Codes** [comment]
> Please add a changelog entry. You can see the details on how in `news/README.txt`.

I have added can you kindly check 

> Please add a changelog entry. You can see the details on how in `news/README.txt`.

I have Added .. Can you Kindly check ...

**Comment by htgoebel** [comment]
@Legorooj IMHO more important: The file is missing a copyright/license header.

**Comment by Legorooj** [comment]
@htgoebel thanks for pointing that out - probably would have spotted it next check but who knows?

@LP-Codes please add the GPL header. This can be found in `LICENSE.GPL.txt`.

**Pull request merged**
