### PR TITLE
hooks: add hook for adbutils

### PR DESCRIPTION
**Pull request by eric15342335**
adbutils bundles [adb binaries](https://github.com/openatx/adbutils/tree/master/adbutils/binaries) for windows/macos as the fallback adb:

https://github.com/openatx/adbutils/blob/dccec86376ab3fd741cfedb62c0c9b71a58b4877/adbutils/_utils.py#L29-L41

[CI](https://github.com/eric15342335/pyinstaller-hooks-contrib/actions/runs/1265028870)

### CODE REVIEW

**Review by bwoodsend — APPROVED** [review]

**Comment by bwoodsend** [comment]
Nice one Eric!

**Comment by rokm** [comment]
I take it this should close #6236?

**Comment by JustinDBruce** [comment]
I pulled down the newly added code, but am still having the same issue. [](https://github.com/pyinstaller/pyinstaller/issues/6236)

**Comment by rokm** [comment]
@JustinDBruce Can you make a onedir build and check if `adb.exe` is now collected in the bundle (i.e., `dist/<name>/adbutils/binaries`)?

**Comment by JustinDBruce** [comment]
Yes it is, I also have it added to the datas in the spec file. So it is in two places now. In the binaries and in main folder along with the exe.

**Comment by rokm** [comment]
Ah, yes, the noconsole + onefile variant is indeed broken...

**Pull request merged**
