### PR TITLE
hooks - Add Hook for docx2pdf

### PR DESCRIPTION
**Pull request by LP-Codes**
_**Added Hook for docx2pdf**_

### CODE REVIEW

**Comment by eric15342335** [comment]
[Present tense](https://pyinstaller.readthedocs.io/en/latest/development/commit-messages.html#the-first-line).

**Comment by bwoodsend** [comment]
And we still need the news item.

**Review by bwoodsend — APPROVED** [review]

**Comment by bwoodsend** [comment]
Thanks @LP-Codes!

**Comment by LP-Codes** [comment]
> Thanks @LP-Codes!

Thanks @bwoodsend  kindly Pardon for the messed up commits

**Pull request merged**
