### PR TITLE
Add hook for Hydra config system (hydra-core)

### LINKED ISSUE #424: Support Hydra config system
[Hydra](https://github.com/facebookresearch/hydra) is a composable config system and CLI parser. One use for it is as a config system for complex servers complete with logs and config tracking per run. 

**Have you gotten the library to work with pyinstaller?**

No. Using `--collect-all` I am currently stuck at:

```sh
Traceback (most recent call last):
  File "nicepipe\__main__.py", line 130, in <module>
  File "hydra\main.py", line 48, in decorated_main
  File "hydra\_internal\utils.py", line 324, in _run_hydra
  File "hydra\_internal\utils.py", line 181, in create_automatic_config_search_path
  File "hydra\_internal\utils.py", line 194, in create_config_search_path
  File "hydra\core\plugins.py", line 41, in instance
  File "hydra\core\singleton.py", line 17, in instance
  File "hydra\core\singleton.py", line 13, in __call__
  File "hydra\core\plugins.py", line 49, in __init__
  File "hydra\core\plugins.py", line 62, in _initialize
  File "hydra\core\plugins.py", line 257, in _scan_all_plugins
AssertionError
[19908] Failed to execute script '__main__' due to unhandled exception!
```

Seems to be an issue with how they scan for plugins. <https://hydra.cc/docs/advanced/plugins/develop/#plugin-discovery-process>

### PR DESCRIPTION
**Pull request by rokm**
Closes #424.

### CODE REVIEW

**Review by bwoodsend — APPROVED** [review]

**Comment by matinmoezzi** [comment]
Hi,
python 3.8.19
hydra-core version = 1.3.2
pyinstaller version = 6.9.0
It seems that `hydra-plugins` issue is not still solved.
```
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    app()
  File "hydra/main.py", line 94, in decorated_main
  File "hydra/_internal/utils.py", line 337, in _run_hydra
  File "hydra/_internal/utils.py", line 190, in create_automatic_config_search_path
  File "hydra/_internal/utils.py", line 203, in create_config_search_path
  File "hydra/core/plugins.py", line 46, in instance
  File "hydra/core/singleton.py", line 17, in instance
  File "hydra/core/singleton.py", line 13, in __call__
  File "hydra/core/plugins.py", line 54, in __init__
  File "hydra/core/plugins.py", line 71, in _initialize
  File "hydra/core/plugins.py", line 186, in _scan_all_plugins
AttributeError: 'PyiFrozenImporter' object has no attribute 'find_module'
[45564] Failed to execute script 'main' due to unhandled exception!
```

**Comment by rokm** [comment]
>  It seems that `hydra-plugins` issue is not still solved.

See https://github.com/facebookresearch/hydra/pull/2531. We have no plans of reverting pyinstaller/pyinstaller#7344.

**Comment by rokm** [comment]
Although on the other hand, we can also work around this on our side by collecting those plugins as source .py files only, if we detect python < 3.10 and PyInstaller >= 5.8: https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/760.

**Comment by matinmoezzi** [comment]
@rokm Thank you so much. I upgraded python=3.8 to 3.10 and it solved the issue.

**Pull request merged**
