### PR TITLE
Updated sound_lib hook

### PR DESCRIPTION
**Pull request by NicklasTegner**

### CODE REVIEW

**Review by bwoodsend — APPROVED** [review]
It's generally encouraged that you only include the binary types you need. You could even use `sound_lib.find_datafiles()` in the hook to only get those your compiling for.

Also I see this is your own package. You can keep your hooks in your own package rather than sending them to us...

**Comment by NicklasTegner** [comment]
Incorrect. This is not originally my own package. Only reason I had it on GitHub, was because the original authors custom repository was down, and he hadn't put it on GitHub yet (which he now has)

**Comment by Legorooj** [comment]
Again; what's the rationale for this change?

**Comment by NicklasTegner** [comment]
The rationale for this change is, that since you have dll files in the library directory for this module regardless of the os, it fails on MacOS with an Unknown/Invalid Header when trying to package it (since it's also trying to read the dll files)

**Comment by NicklasTegner** [comment]
For reference, here is the traceback I'm getting on MacOS, but not on Windows.

Note: I have removed some of PyInstallers output for other hooks.

> 4753 INFO: Analyzing /Users/nicklas/Desktop/python-projects/soundlibtest/test.py
4867 INFO: Processing module hooks...
4868 INFO: Loading module hook 'hook-sound_lib.py' from '/usr/local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5092 INFO: Looking for dynamic libraries
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 720, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 667, in build
    exec(code, spec_namespace)
  File "/Users/nicklas/Desktop/python-projects/soundlibtest/test.spec", line 6, in <module>
    a = Analysis(['test.py'],
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 242, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 466, in assemble
    self.binaries.extend(bindepend.Dependencies(self.binaries,
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 230, in Dependencies
    for lib, npth in selectImports(pth, xtrapath):
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 504, in selectImports
    dlls = getImports(pth)
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 745, in getImports
    return _getImports_macholib(pth)
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 628, in _getImports_macholib
    m = MachO(pth)
  File "/usr/local/lib/python3.8/site-packages/macholib/MachO.py", line 118, in __init__
    self.load(fp)
  File "/usr/local/lib/python3.8/site-packages/macholib/MachO.py", line 133, in load
    self.load_header(fh, 0, size)
  File "/usr/local/lib/python3.8/site-packages/macholib/MachO.py", line 167, in load_header
    raise ValueError("Unknown Mach-O header: 0x%08x in %r" % (header, fh))
ValueError: Unknown Mach-O header: 0x7f454c46 in <_io.BufferedReader name='/usr/local/lib/python3.8/site-packages/sound_lib/lib/x86/libbassopus.so'>

**Comment by Legorooj** [comment]
@NicklasTegner can you please rework this PR to use the `collect_data_files` function's `includes` and `excludes` arguments? And assign it to `binaries` as well.

**Pull request closed without merging**
