### PR TITLE
hooks: add hook for branca

### PR DESCRIPTION
**Pull request by eric15342335**

### CODE REVIEW

**Comment by eric15342335** [comment]
Wait. The pull request already exists. Pointing to #61
I am closing this.

**Comment by rokm** [comment]
I think at this point, it's better if we merge this one and close the other one.

**Comment by eric15342335** [comment]
> I think at this point, it's better if we merge this one and close the other one.

Consider merging the folium hook too.

**Comment by rokm** [comment]
> Consider merging the folium hook too.

Will do. I think `folium` depends on `branca˙, so we need this hook merged first, anyway.

**Review by rokm — APPROVED** [review]

**Review by bwoodsend — APPROVED** [review]
And [I see you've done CI](https://github.com/eric15342335/pyinstaller-hooks-contrib/actions/runs/1220480010) too.

**Pull request merged**
