### PR TITLE
Create 72.new.rst

### PR DESCRIPTION
**Pull request by skipmcgee**
New Hook

Adding hook for the countryinfo module data

### CODE REVIEW

**Review by bwoodsend — CHANGES_REQUESTED** [review]
I'm afraid this needs quite a bit of work:

1. Put separate hooks into separate pull requests (so remove one of them and open a new PR for it).
2. They both need news entries (see the news/Readme.txt file).
3. The copyright disclaimer needs to go at the top of each file (copy it from another hook) or their not protected.
4. And you'll need to appease flake8 (by putting a newline at the end of the pycountry hook).

**Review by bwoodsend — CHANGES_REQUESTED** [review]
I'm afraid this needs quite a bit of work:

1. Put separate hooks into separate pull requests (so remove one of them and open a new PR for it).
2. They both need news entries (see the news/Readme.txt file).
3. The copyright disclaimer needs to go at the top of each file (copy it from another hook) or their not protected.
4. And you'll need to appease flake8 (by putting a newline at the end of the pycountry hook).

**Comment by skipmcgee** [comment]
Thanks for your help!

Put separate hooks into separate pull requests (so remove one of them and open a new PR for it).
 - completed, PR 74
They both need news entries (see the news/Readme.txt file).
 - completed
The copyright disclaimer needs to go at the top of each file (copy it from another hook) or their not protected.
 - completed
And you'll need to appease flake8 (by putting a newline at the end of the pycountry hook).
 - completed

Also I realized that there is already a pycountry hook, it just doesn't import the pycountry.db, so I added that component to the hook.

Thanks very much for your help and let me know if I need to adjust anything!

**Comment by rokm** [comment]
I think there might have been a misunderstanding... 

The idea is to modify the existing `pycountry` hook in one PR, and to add a new hook for `countryinfo` in a separate PR. (= each PR should be self-contained, and should modify a hook for a single package).

The news fragments need to be added into these two PRs (and not separate ones), because they reflect the changes made by each PR.

The news fragment for the `pycountry` PR should be named `NUM.update.rst`, because you are updating an existing hook.

So for example, edit this PR to:
- modify `hook-pycountry.py`
- add `news/72.update.rst` that describes the change

and edit PR 73 to:
- add `hook-countryinfo.py`
- add `news/73.new.rst` that describes the change

And the news message is misleading, too - these packages do not need a hidden import, but rather need their metadata and data collected.

**Comment by bwoodsend** [comment]
> - add news/72.update.rst that describes the change

When doing this be sure to mention the version of `pycountry`.

**Pull request closed without merging**
