### PR TITLE
add hook for workflow

### PR DESCRIPTION
**Pull request by zhouronghua**
need to hook for workflow

### CODE REVIEW

**Comment by bwoodsend** [comment]
Ahh I see this is already merged. @Legorooj Would it be easier to revert and ask zhouronghua to correct the name or just sort it ourselves?

**Comment by Legorooj** [comment]
I didn't notice that, so good catch, but the number is actually semi-valid: #19. There's probably no point changing it now, cause that issue links back to this PR (albeit in a roundabout manner).

In this case, amending the commit locally and pushing is probably the easiest thing - I enabled force pushing to this repository. When you get write access to the main PyInstaller repository remember you _can't_ force push, so no history rewriting. Check 5 times more than necesarry before merging something on the main repo.

**Comment by zhouronghua** [comment]
> Ahh I see this is already merged. @Legorooj Would it be easier to revert and ask zhouronghua to correct the name or just sort it ourselves?

sorry, not familier with the workflow, i thought the number was the issue i just generate, but in fact it is the pull request no

**Comment by Legorooj** [comment]
@zhouronghua issues and PRs share the numbers, so if there's no issue for it already, then just use the PR number.

**Comment by zhouronghua** [comment]
> @zhouronghua issues and PRs share the numbers, so if there's no issue for it already, then just use the PR number.
i get it, thank u

**Comment by bwoodsend** [comment]
There we go. Sorted now. @zhouronghua For future reference - the `xxx.new.rst` file goes in the `news/` folder rather than the root. Other than that - good work!

**Pull request merged**
