### PR TITLE
hooks: add hook for jieba

### PR DESCRIPTION
**Pull request by BLKSerene**
This PR adds a hook for [jieba](https://github.com/fxsjy/jieba) which is a Chinese word tokenization library.

### CODE REVIEW

**Comment by bwoodsend** [comment]
Hmm, the pull request is good but I'm rather uncomfortable with the library itself. I just opened up a file randomly to see what it does with its data files and I see [this](https://github.com/fxsjy/jieba/blob/67fa2e36e72f69d9134b8a1037b83fbb070b9775/jieba/_compat.py#L23-L24) accessing data files from the wrong place, [this](https://github.com/fxsjy/jieba/blob/67fa2e36e72f69d9134b8a1037b83fbb070b9775/jieba/_compat.py#L32) trying to install a package on the fly into potentially the wrong Python environment (which wouldn't work with PyInstaller) and [a version comparison](https://github.com/fxsjy/jieba/blob/67fa2e36e72f69d9134b8a1037b83fbb070b9775/jieba/_compat.py#L39) which will break when `paddle 1.10.0` is released.

I'm happy to accept the pull request but I want you to be aware that I'm more likely to just mark the test as skipped and ignore this library than fix it at the first sign of `jieba` induced trouble.

**Comment by BLKSerene** [comment]
The issue of installing `paddlepaddle` and the version comparison issue would occur when `enable_paddle` is called to use the paddle mode of `jieba`. For my use cases, it is fine.

There have been no updates for the library for several years, and I don't think they would have the time to review PRs even if submit one. So, shall I just remove the test?

**Comment by bwoodsend** [comment]
If they're not publishing releases then that test will probably never run again (at least not automatically) so it doesn't make much difference whether or not it stays. @rokm What do you reckon? I say we just merge as is?

**Comment by rokm** [comment]
Yes, let's merge as-is. We'll deal with any trouble rising from updates if/when they actually happen.

**Pull request merged**
