### PR TITLE
Add hook for "shotgun_api3"

### PR DESCRIPTION
**Pull request by fabiangeisler**
This is a hook for the [Shotgrid python API](https://github.com/shotgunsoftware/python-api).

Let me know if there is something missing/wrong with this PR! 🙂

### CODE REVIEW

**Comment by bwoodsend** [comment]
I've been knocking together a PR checklist over on #130. Mind guineapig-ing it? You can see it rendered [here](https://github.com/bwoodsend/pyinstaller-hooks-contrib/tree/readme#i-want-to-help). That said, you've managed to guess most of it correctly. You just need a [news entry](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/news/README.txt).

**Comment by fabiangeisler** [comment]
I added the missing news entry and gave your guide a read through. There is nothing left to add from what I can see. Thanks for checking this PR and writing the guide! 🙂

**Review by bwoodsend — APPROVED** [review]
Ok, [CI is happy](https://github.com/bwoodsend/pyinstaller-hooks-contrib/actions/runs/979763018) (minus losing connection to the internet half way through anyway).

**Comment by bwoodsend** [comment]
Cheers @fabiangeisler!

**Pull request merged**
