### PR TITLE
hooks: add hooks for LaoNLP and PyThaiNLP

### PR DESCRIPTION
**Pull request by BLKSerene**
This PR adds a hook for [LaoNLP](https://github.com/wannaphong/LaoNLP), which is an NLP library for Lao (Laotian).
Another hook for [PyThaiNLP](https://github.com/PyThaiNLP/pythainlp), which is an NLP library for the Thai language, is also added.

### CODE REVIEW

**Comment by BLKSerene** [comment]
Waiting for my patch to `LaoNLP` to be merged...

**Comment by bwoodsend** [comment]
Looks like this `pythianlp` package [also needs a `collect_data_files()` hook](https://github.com/pyinstaller/pyinstaller-hooks-contrib/actions/runs/6277852697/job/17050421794?pr=644#step:10:623).

**Comment by BLKSerene** [comment]
And now waiting my patch for fixing `tzdata` dependency on Windows to be merged to `PyThaiNLP`...

**Comment by BLKSerene** [comment]
@bwoodsend Should be okay now. Dependency issues with `tzdata` on Windows has been fixed in the latest beta version of `PyThaiNLP`.

**Review by rokm — APPROVED** [review]

**Pull request merged**
